apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: qobs67xkx-nodejs 
  janus-idp.io/tekton: qobs67xkx-nodejs
  backstage.io/kubernetes-id: qobs67xkx-nodejs
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: qobs67xkx-nodejs
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  